// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NslAPI.Data;

namespace NslAPI.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NslAPI.Data.Fees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AmountPaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfPayment")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Fees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPaid = 200,
                            DateOfPayment = new DateTime(2022, 2, 23, 15, 21, 2, 164, DateTimeKind.Local).AddTicks(2605),
                            FeeType = "Member",
                            MemberId = 1
                        },
                        new
                        {
                            Id = 2,
                            AmountPaid = 200,
                            DateOfPayment = new DateTime(2022, 2, 23, 15, 21, 2, 167, DateTimeKind.Local).AddTicks(6528),
                            FeeType = "Member",
                            MemberId = 2
                        },
                        new
                        {
                            Id = 3,
                            AmountPaid = 100,
                            DateOfPayment = new DateTime(2022, 2, 23, 15, 21, 2, 167, DateTimeKind.Local).AddTicks(6577),
                            FeeType = "Jersey",
                            MemberId = 2
                        });
                });

            modelBuilder.Entity("NslAPI.Data.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOKPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextOfKin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Postcode")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Ngunnawal",
                            DOB = new DateTime(1984, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dhanuka.singhe@gmail.com",
                            FName = "Dhanuka",
                            HomePhone = "",
                            IsActive = 1,
                            LName = "Ilandarage",
                            MName = "Sudheera",
                            Mobile = "0432009680",
                            NOKPhone = "0432000222",
                            NextOfKin = "Ryan",
                            Postcode = 2913,
                            ProfilePicture = "",
                            Relationship = "Son",
                            State = "ACT",
                            Street = "7 Igera Place"
                        },
                        new
                        {
                            Id = 2,
                            City = "Ngunnawal",
                            DOB = new DateTime(2014, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ryan.singhe@gmail.com",
                            FName = "Ryan",
                            HomePhone = "",
                            IsActive = 1,
                            LName = "Ilandarage",
                            MName = "Harindu",
                            Mobile = "0432222000",
                            NOKPhone = "0432333999",
                            NextOfKin = "Pavithri",
                            Postcode = 2913,
                            ProfilePicture = "",
                            Relationship = "Mom",
                            State = "ACT",
                            Street = "7 Igera Place"
                        });
                });

            modelBuilder.Entity("NslAPI.Data.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BattingStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BowlingStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JerseyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JerseyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JerseySize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("PlayingRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BattingStyle = "Left",
                            BowlingStyle = "Right arm Medium Pace",
                            JerseyName = "Sudeera",
                            JerseyNumber = "23",
                            JerseySize = "M",
                            MemberId = 1,
                            PlayingRole = "Allrounder"
                        });
                });

            modelBuilder.Entity("NslAPI.Data.Fees", b =>
                {
                    b.HasOne("NslAPI.Data.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("NslAPI.Data.Player", b =>
                {
                    b.HasOne("NslAPI.Data.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
